"""Gate-initialisation study: one table + one figure from the published runs.

Reads r04-r13 straight from the `kaggle-results` branch (nothing is retyped) and
writes figures/init/:
    init_runs.csv     one row per GLA run: init, seed, recall per load, steps to
                      0.5 held-out recall, layer-0 retention and bias, keep-L0 clamp
    INIT.md           the same as markdown tables, plus the group means
    init_figure.png   A capacity by init (mean + seed range), B training curves,
    init_figure.pdf   C layer-0 forgetting vs recall at 32 facts

    python -m scripts.init_study            # after `git fetch origin kaggle-results`
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import os
import statistics as st
import subprocess

# init -> [(run, seed)]. Zero gate weight everywhere except legacy (small random weight).
GROUPS = {
    "legacy": [("r04", 0), ("r05", 1), ("r06", 2)],
    "bias0": [("r09", 0), ("r10", 1), ("r12", 2)],
    "bias2": [("r08", 0), ("r11", 1), ("r13", 2)],
    "bias6": [("r07", 0)],
}
LABEL = {"legacy": "legacy (bias 0, random W)", "bias0": "γ₀ = 0.5 (bias 0)",
         "bias2": "γ₀ = 0.88 (bias 2)", "bias6": "γ₀ = 0.9975 (bias 6)"}
SHORT = {"legacy": "legacy", "bias0": "γ₀ 0.5", "bias2": "γ₀ 0.88", "bias6": "γ₀ 0.9975"}
GAMMA0 = {"legacy": 0.5, "bias0": 0.5, "bias2": 0.881, "bias6": 0.9975}
# reference palette (dataviz skill), validated all-pairs for these three hues; legacy = neutral reference
COLOR = {"legacy": "#9a9994", "bias0": "#2a78d6", "bias2": "#eb6834", "bias6": "#1baf7a"}
MARKER = {"legacy": "s", "bias0": "o", "bias2": "^", "bias6": "D"}
LOADS = (2, 4, 8, 16, 32, 64, 128)
INK, INK2, GRID = "#0b0b0b", "#52514e", "#e6e5e1"


def _show(ref: str, path: str) -> str:
    return subprocess.check_output(["git", "show", f"{ref}:{path}"], stderr=subprocess.DEVNULL).decode()


def _csv(ref, path):
    return list(csv.DictReader(io.StringIO(_show(ref, path))))


def load(ref: str = "origin/kaggle-results") -> list:
    rows = []
    for init, runs in GROUPS.items():
        for run, seed in runs:
            base = f"runs/{run}"
            p1 = {int(r["n_bindings"]): float(r["accuracy_per_query"])
                  for r in _csv(ref, f"{base}/pass1_capacity.csv") if r["model"].startswith("gated_linear")}
            hist = json.loads(_show(ref, f"{base}/gated_linear_sweep.json"))["history"]["eval_acc"]
            curve = [(e["step"], e.get("by_mode", {}).get("assoc_recall", 0.0)) for e in hist]
            to_half = next((s for s, v in curve if v >= 0.5), None)
            g = [r for r in _csv(ref, f"{base}/pass8_gates.csv")
                 if r["model"].startswith("gated_linear") and r["n_bindings"] == "32"
                 and ".blocks.0." in r["layer"] and r["role"] == "set_value"][0]
            c = [r for r in _csv(ref, f"{base}/pass9_clamp.csv")
                 if r["model"].startswith("gated_linear") and r["n_bindings"] == "32" and r["condition"] == "keep_L0"][0]
            rows.append({"run": run, "init": init, "gamma0": GAMMA0[init], "seed": seed,
                         **{f"recall_{nb}": p1[nb] for nb in LOADS},
                         "steps_to_0.5": to_half if to_half is not None else "",
                         "final_step": curve[-1][0], "final_heldout": round(curve[-1][1], 3),
                         "l0_log10_retention": float(g["fact_log10_retention"]),
                         "l0_bias": float(g["bias_mean"]),
                         "keep_l0_delta_32": float(c["delta"]), "curve": curve})
    return rows


def write_tables(rows, out):
    cols = [k for k in rows[0] if k != "curve"]
    with open(os.path.join(out, "init_runs.csv"), "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        w.writerows([{k: r[k] for k in cols} for r in rows])
    md = ["# Gate-initialisation study (GLA)", "",
          "Generated by `scripts/init_study.py` from the `kaggle-results` branch. Same data, schedule, lr and size in",
          "every run; only the decay gate's initial bias (and, for legacy, a small random gate weight) and the seed differ.", "",
          "## Per-query recall by load (pass 1): group mean [min–max over seeds]", "",
          "| facts | " + " | ".join(LABEL[i] for i in GROUPS) + " |", "|---:|" + "---|" * len(GROUPS)]
    for nb in LOADS:
        cells = []
        for init in GROUPS:
            v = [r[f"recall_{nb}"] for r in rows if r["init"] == init]
            cells.append(f"{st.mean(v):.3f} [{min(v):.2f}–{max(v):.2f}]" if len(v) > 1 else f"{v[0]:.3f} (1 seed)")
        md.append(f"| {nb} | " + " | ".join(cells) + " |")
    md += ["", "## Per run", "",
           "| run | init | seed | recall @32 | recall @64 | steps to 0.5 | layer-0 retention (log10) | layer-0 bias | keep-L0 Δ @32 |",
           "|---|---|---:|---:|---:|---:|---:|---:|---:|"]
    for r in rows:
        md.append(f"| {r['run']} | {LABEL[r['init']]} | {r['seed']} | {r['recall_32']:.3f} | {r['recall_64']:.3f} | "
                  f"{r['steps_to_0.5'] or 'never'} | {r['l0_log10_retention']:.0f} | {r['l0_bias']:+.2f} | "
                  f"{r['keep_l0_delta_32']:+.3f} |")
    md += ["", "Steps to 0.5 = first eval (every 500 steps) where held-out multi-query recall reaches 0.5; 15,000-step cap.",
           "Layer-0 retention = mean log10 share of a fact value's write still in layer 0's state at the first question.",
           "keep-L0 Δ = recall change when layer 0's gate is clamped to σ(6) at eval time (pass 9)."]
    with open(os.path.join(out, "INIT.md"), "w") as fh:
        fh.write("\n".join(md) + "\n")


def make_figure(rows, out):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({"font.size": 9, "axes.edgecolor": INK2, "axes.labelcolor": INK2, "xtick.color": INK2,
                         "ytick.color": INK2, "axes.spines.top": False, "axes.spines.right": False,
                         "font.family": "DejaVu Sans"})
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 4.3), gridspec_kw={"width_ratios": [1.15, 1.15, 1.0]})
    by = {i: [r for r in rows if r["init"] == i] for i in GROUPS}

    def style(ax, title, sub):
        ax.set_title(title, loc="left", fontsize=10.5, fontweight="bold", color=INK, pad=20)
        ax.text(0, 1.035, sub, transform=ax.transAxes, fontsize=8.5, color=INK2)
        ax.grid(True, color=GRID, linewidth=0.7)
        ax.set_axisbelow(True)

    # A: capacity
    ax = axes[0]
    ends = {}
    for init in ("legacy", "bias2", "bias6", "bias0"):  # accent drawn last, on top
        rs = by[init]
        mean = [st.mean(r[f"recall_{nb}"] for r in rs) for nb in LOADS]
        if len(rs) > 1:
            lo = [min(r[f"recall_{nb}"] for r in rs) for nb in LOADS]
            hi = [max(r[f"recall_{nb}"] for r in rs) for nb in LOADS]
            ax.fill_between(LOADS, lo, hi, color=COLOR[init], alpha=0.16, linewidth=0)
        ax.plot(LOADS, mean, color=COLOR[init], linewidth=2, marker=MARKER[init], markersize=5.5,
                markeredgecolor="white", markeredgewidth=0.8, linestyle="--" if init == "bias6" else "-")
        ends[init] = mean
    ax.set_xscale("log", base=2)
    ax.set_xticks(LOADS, [str(n) for n in LOADS])
    ax.set_ylim(-0.02, 1.04)
    ax.set_xlabel("facts in the prompt (log scale)")
    ax.set_ylabel("per-query recall")
    # direct labels past the last load, stacked where lines converge, with short leaders
    ax.set_xlim(1.6, 420)
    for init, y in (("legacy", None), ("bias0", None), ("bias6", 0.13), ("bias2", 0.035)):
        end = ends[init][-1]
        ty = end if y is None else y
        ax.annotate(SHORT[init] + (" (1 seed)" if init == "bias6" else ""), (128, end), xytext=(170, ty),
                    textcoords="data", fontsize=8, color=INK2, ha="left", va="center",
                    arrowprops=None if y is None else dict(arrowstyle="-", color=GRID, linewidth=0.8))
    style(ax, "A · γ₀ = 0.5 learns recall far better than 0.88 or 0.9975",
          "pass 1 · lines = mean over seeds 0–2, bands = min–max")

    # B: training curves
    ax = axes[1]
    for init in ("legacy", "bias2", "bias6", "bias0"):
        for r in by[init]:
            s, v = zip(*r["curve"])
            ax.plot([x / 1000 for x in s], v, color=COLOR[init], linewidth=1.6 if init == "bias0" else 1.3,
                    alpha=0.95 if init != "legacy" else 0.85, linestyle="--" if init == "bias6" else "-")
    ax.axhline(0.5, color=INK2, linewidth=0.8, linestyle=":")
    ax.text(0.2, 0.515, "0.5", fontsize=7.5, color=INK2)
    ax.set_xlim(0, 15.5)
    ax.set_ylim(-0.02, 1.0)
    ax.set_xlabel("training step (thousands)")
    ax.set_ylabel("held-out recall, full difficulty")
    style(ax, "B · γ₀ = 0.5 learns faster",
          "held-out recall per run · 0.5 at 5–10.5k steps vs 13k or never")

    # C: mechanism
    ax = axes[2]
    for init in GROUPS:
        for r in by[init]:
            ax.scatter(r["l0_log10_retention"], r["recall_32"], s=46, color=COLOR[init], marker=MARKER[init],
                       edgecolor="white", linewidth=0.8, zorder=3)
            off = (-6, -11) if r["run"] == "r09" else (4, 4)   # r09 sits beside r04
            ax.annotate(r["run"], (r["l0_log10_retention"], r["recall_32"]), xytext=off,
                        textcoords="offset points", fontsize=7, color=INK2, ha="right" if off[0] < 0 else "left")
    ax.set_xlim(-205, 12)
    ax.set_ylim(-0.02, 1.04)
    ax.set_xlabel("layer-0 retention of a fact at the first question (log10)\n← forgets faster")
    ax.set_ylabel("per-query recall at 32 facts")
    style(ax, "C · Working runs forget fast in layer 0",
          "one point per run · passes 8 and 1")

    handles = [plt.Line2D([], [], color=COLOR[i], marker=MARKER[i], linewidth=2, markersize=6,
                          markeredgecolor="white", linestyle="--" if i == "bias6" else "-", label=LABEL[i])
               for i in ("bias0", "bias2", "bias6", "legacy")]
    fig.legend(handles=handles, loc="lower center", ncol=4, frameon=False, fontsize=8.5,
               bbox_to_anchor=(0.5, -0.01))
    fig.text(0.008, 0.985, "Gate-initialisation study · GLA, 5 layers, 2.67M params · zero gate weight unless legacy · "
             "same data, schedule and lr in every run", fontsize=8, color=INK2, va="top")
    fig.tight_layout(rect=(0, 0.06, 1, 0.95), w_pad=2.5)
    for ext in ("png", "pdf"):
        fig.savefig(os.path.join(out, f"init_figure.{ext}"), dpi=200, facecolor="#fcfcfb")
    plt.close(fig)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ref", default="origin/kaggle-results")
    ap.add_argument("--out", default="figures/init")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    rows = load(args.ref)
    write_tables(rows, args.out)
    make_figure(rows, args.out)
    print(f"wrote {args.out}/ (init_runs.csv, INIT.md, init_figure.png/.pdf) from {len(rows)} runs")


if __name__ == "__main__":
    main()
